### ISSUE TITLE
Add ability to set "GitHub hook trigger for GITScm polling" for job on suite level

### ISSUE THREAD

**Issue by SergeiZagriychuk** [zebrunner/qps-pipeline#284]
Idea: we need it to be able to trigger **test** job after push to **dev** repo

For that we need next values to be populated into Jenkins job configuration from testng suite xml:
1) GitHub project - Project url (URL of configured **dev** repo)
2) Checkbox 'GitHub hook trigger for GITScm polling'(we will pass 'true' in suite to enable the feature)
3) Quiet period (time to wait till job will be executed after triggering, to wait till dev build is properly deployed on env)

**Comment by vdelendik** [comment]
returned to TBD as there are limitations in binding to different dev&qa repositories

**Comment by vdelendik** [comment]
it seems like can be organized with 
https://github.com/qaprosoft/zafira/issues/1319

**Comment by vdelendik** [comment]
closing as won't fix as we are going to reuse generic webhook
