### ISSUE TITLE
Duplicate params are in Job title on Stage View

### ISSUE THREAD

**Issue by okamara** [zebrunner/qps-pipeline#613]
Steps:
1. open web.xml and declare 
<parameter name="jenkinsRegressionPipeline" value="Carina-Demo-Regression-Pipeline"/>

        <parameter name="jenkinsRegressionMatrix" value="branch: 601test, browser: chrome, language: fr_FR; branch: 602test, browser:firefox, browser_version:69"/>
	<parameter name="jenkinsPipelineBrowsers" value="browser: chrome; browser: firefox"/>
2. Commit 
3. In Jenkins run Carina-Demo-Regression-Pipeline job
4. Open Stage View and verify that title of web jobs shows correct params 
Actual result: Duplicate params are in Job title on Stage View(see image)
<img width="404" alt="Screen Shot 2020-01-29 at 4 22 02 PM" src="https://user-images.githubusercontent.com/32964663/73361711-8d47de80-42b6-11ea-86d0-4420eb9c22cf.png">

**Comment by vdelendik** [comment]
closing as won't fix
