### ISSUE TITLE
move to zebrunner org and reset release numbers

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/qps-pipeline#887]
it seems like we can start with 1.1 version to be in sync with zebrunner community edition releases

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/qps-pipeline
as a testing scenario verify that old qps-pipeline git url works fine, i.e do sanity check for [zebrunner](https://github.com/zebrunner/zebrunner) using develop branch

**Comment by okamara** [comment]
Verified. Fixed.
