### ISSUE TITLE
hub_mode should be renamed to provider or capabilities.provider

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/qps-pipeline#912]
We’ve lost possibility to setup default selenium hub provider for the CI.
need rename global config properties to be able to override it by global env var on Jenkins:

https://github.com/zebrunner/qps-pipeline/blob/a120f8dbcae4489f18faf939c065bf1e4032215a/src/com/qaprosoft/jenkins/pipeline/Configuration.groovy#L73

**Comment by vdelendik** [comment]
fixed.
during the testing please review web-demo-test job console log. It should have such text inside:
_capabilities.provider=selenium_
and of coure web job should be executed correctly

**Comment by dhreben** [comment]
Fixed:
<img width="603" alt="Screen Shot 2020-10-06 at 19 15 56" src="https://user-images.githubusercontent.com/50950954/95228731-5ee8ae80-0808-11eb-9aa7-74a8876c8668.png">
